name: tweetup_fyp
description: A new Flutter project.


publish_to: 'none' # Remove this line if you wish to publish to pub.dev


version: 1.0.0+1

environment:
  sdk: '>=2.18.2 <3.0.0'


dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.5
  firebase_auth: ^4.1.1
  cloud_firestore: ^4.0.4
  firebase_core: ^2.1.1
  google_sign_in: ^5.4.2
  provider: ^6.0.4
  google_fonts: ^3.0.1
  flutter_phoenix: ^1.1.0
  flutter_spinkit: ^5.1.0
  url_launcher: ^6.1.6
  mailto: ^2.0.0
  flutter_speed_dial: ^6.2.0
  flutter_svg: ^1.1.6
  shared_preferences: ^2.0.15
  fluttericon: ^2.0.0
  firebase_storage: ^11.0.4
  file_picker: ^5.2.2
  awesome_dialog: ^3.0.2
  firebase_messaging: ^14.0.4
  flutter_local_notifications: ^12.0.3
  http: ^0.13.5
  image_picker: ^0.8.6
  percent_indicator: ^4.2.2
  another_flushbar: ^1.12.29
  flutter_easyloading: ^3.0.5
  flutter_native_splash: ^2.2.14

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^2.0.1


flutter_native_splash:
  color: "#ffffff"
  android_12:
  android: true
  ios: true
  image: assets/images/appIcon.png




flutter:

  uses-material-design: true

  assets:
    - assets/images/


  # example:
  # fonts:
  #   - family: Schyler
  #     fonts:
  #       - asset: fonts/Schyler-Regular.ttf
  #       - asset: fonts/Schyler-Italic.ttf
  #         style: italic
  #   - family: Trajan Pro
  #     fonts:
  #       - asset: fonts/TrajanPro.ttf
  #       - asset: fonts/TrajanPro_Bold.ttf
  #         weight: 700
  #